### ISSUE TITLE
spine旋转270度

### ISSUE THREAD

**Issue by ankye** [qcdong2016/PlistDumper#2]
非常有效，不过spine里面atlas是旋转270度，😄，不确定其他是90还是270度

**Comment by qcdong2016** [comment]
是吗，有例子吗

**Comment by ankye** [comment]
https://github.com/wheelpharaoh/gs-assets/blob/d250f1468eee71c885bdda6924ed63752527d9ae/character/chara_1020.atlas

**Comment by qcdong2016** [comment]
修复了。之前没注意spine是270度
