### ISSUE TITLE
文件级的导出仿佛无效，文件夹的导出很好用，希望作者添加一个

### ISSUE THREAD

**Issue by lonelyone007** [qcdong2016/PlistDumper#5]
![image](https://user-images.githubusercontent.com/7918742/207905164-ce645a21-d244-4f50-9e84-d1b303c4d1cc.png)

**Comment by qcdong2016** [comment]
什么意思呢

**Comment by lonelyone007** [comment]
就是用命令针对plist文件导出仿佛没有效果，只有参数是文件夹的时候才能导出。
我是windows平台。
