### ISSUE TITLE
纯纯小白有个问题：用啥运行命令啊？

### ISSUE THREAD

**Issue by SUIGANGLASHUEN** [qcdong2016/PlistDumper#6]
直接运行exe会自动解析plist，但是不会解析atlas。不会用命令行，提示'PlistDumper' 不是内部或外部命令，也不是可运行的程序。用windows powershell提示PlistDumper : 无法将“PlistDumper”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，
请确保路径正确，然后再试一次。
麻烦大佬指导一下

**Comment by qcdong2016** [comment]
那你先学学怎么用命令。
